### ISSUE TITLE
assistant_grpc_demo_snowboy.py credentials/activity controls

### ISSUE THREAD

**Issue by sstgohanx** [senyoltw/custom-hotword-for-aiy-voicekit#7]
Hello,

It appears when using assistant_grpc_demo_snowboy.py , the credentials/activity controls are lost. I'm unsure if this may be due to the client ID or client secret, however it appears that it is linking to my location for weather. The normal 'assistant_library_demo.py' does link to my account (name, location, weather, etc etc).

I also noticed that in order to run, the argument --mode needed to be added. I don't know if this was as intended.

**Comment by mongonta0716** [comment]
Hi, @sstgohanx 

How does it work when using **assistant_grpc_demo.py**?

If it is the same as assistant_grpc_demo_snowboy.py, you need to have [aiyprojects-raspbian](https://github.com/google/aiyprojects-raspbian) correct it.

**Comment by sstgohanx** [comment]
Good morning, @mongonta0716 

Yes, it works within assistant_grpc_demo.py,
I suspect this may be due to the Credentials auth that needs to be done, since it never prompted for the acceptance of credentials under the snowboy mod. It, however, DID prompt for it while under the 'assistant_grpc_demo.py' script.

Thanks,
Best Regards.

**Comment by mongonta0716** [comment]
Good morning (Good night in Japan.）, @sstgohanx

It does not reproduce in my environment.(VoiceKitV2)
Both the normal 'assistant_grpc_demo.py' and 'assistant_grpc_demo_snowboy.py' link to my account (name, location, weather, etc etc).

Since the credentials auth is common between 'normal grpc' and 'snowboy grpc' once authenticated, there should be no difference in behavior between 'normal grpc' and 'snowboy grpc'.

Thanks,
Best Reagards.
